#! /usr/bin/env bash

# Copyright (c) 2025-2026 Daemon Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
repo_dir="$(git rev-parse --show-toplevel)"

# Some LLVM linking tasks may eat up 8GB each.
nproc_count="$("${script_dir}/nproc")"
mem_count="$(echo "$(${script_dir}/freemem) 8" | awk '{r = int($1 / $2); print (r < 1 ? 1 : r)}')"
safer_count="$(echo "${nproc_count} ${mem_count}" | awk '{print ($1 < $2 ? $1 : $2)}')"

echo "Using ${safer_count} jobs"

export CMAKE_BUILD_PARALLEL_LEVEL="${safer_count}"
export MAKEFLAGS="-j${safer_count}"

if [ -z "${USE_CCACHE:-}" ]
then
	if command -v ccache >/dev/null 2>&1
	then
		USE_CCACHE='ON'
	fi
fi

for target_name in "${@}"
do
	conf_file="${script_dir}/conf/${target_name}.conf"

	if [ ! -f "${conf_file}" ]
	then
		echo "WARN: Missing ${target_name} configuration" >&2
		continue
	fi

	echo "Building ${target_name}"

	cmake_args=(-S "${repo_dir}" -G'Unix Makefiles')

	if [ "${CMAKE_DEBUG:-}" = 'ON' ]
	then
		cmake_args+=(--debug-output)
	fi

	if [ "${CMAKE_TRACE:-}" = 'ON' ]
	then
		cmake_args+=(--trace)
	fi

	shared_dir="${repo_dir}/build/shared"

	FORCE_PULL="${FORCE_PULL:-OFF}"

	if [ ! -d "${shared_dir}" ]
	then
		FORCE_PULL='ON'
	fi
	
	if [ "${FORCE_PULL}" = 'ON' ]
	then
		cmake -B "${shared_dir}" "${cmake_args[@]}" -D'CLONE_SHARED_REPOSITORIES'='ON'
		cmake --build "${shared_dir}"
	fi

	cmake_args+=(-D'SHARED_REPOSITORIES_DIR'="${shared_dir}")

	. "${conf_file}"

	if [ -n "${USE_CCACHE:-}" ]
	then
		if [ "${USE_CCACHE}" = 'ON' ]
		then
			echo "Using Ccache"
		fi

		cmake_args+=(-D'USE_CCACHE'="${USE_CCACHE}")
	fi

	if [ -n "${USE_LTO:-}" ]
	then
		if [ "${USE_LTO}" = 'ON' ]
		then
			echo "Using LTO"
		fi

		cmake_args+=(-D'USE_LTO'="${USE_LTO}")
	fi

	if [ -n "${TOOLCHAIN:-}" ]
	then
		cmake_args+=(-D'CMAKE_TOOLCHAIN_FILE'="${repo_dir}/cmake/${TOOLCHAIN}")
	fi
		
	if [ -n "${GCC:-}" ]
	then
		cmake_args+=(-D'CMAKE_C_COMPILER'="${GCC}-gcc")
		cmake_args+=(-D'CMAKE_CXX_COMPILER'="${GCC}-g++")
	fi
		
	if [ -n "${CLANG:-}" ]
	then
		cmake_args+=(-D'CMAKE_C_COMPILER'='clang')
		cmake_args+=(-D'CMAKE_CXX_COMPILER'='clang++')
		cmake_args+=(-D'CMAKE_C_FLAGS'="-target ${CLANG}")
		cmake_args+=(-D'CMAKE_CXX_FLAGS'="-target ${CLANG}")
	fi

	if [ -n "${MACOS:-}" ]
	then
		cmake_args+=(-D'CMAKE_OSX_DEPLOYMENT_TARGET'="${MACOS}")
	fi

	# Variables from target configuration.
	unset TOOLCHAIN
	unset GCC
	unset CLANG
	unset MACOS

	# Variable to only set once
	unset FORCE_PULL

	build_dir="${repo_dir}/build/${target_name}${SUFFIX:-}"

	cmake -B "${build_dir}" "${cmake_args[@]}"
	cmake --build "${build_dir}"

	find "${build_dir}/prefix" -type d -exec rmdir {} \; 2>/dev/null || true
done
