#! /usr/bin/env bash

# Copyright (c) 2026 Daemon Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
export repo_dir="$(git rev-parse --show-toplevel)"

export nproc_count="$("${script_dir}/nproc")"

echo "Using ${nproc_count} jobs"

export SUFFIX="${SUFFIX:-}"

clean_target()
{
	local target_name="${1}"

	local build_dir="${repo_dir}/build/${target_name}${SUFFIX:-}"

	make -C"${build_dir}" -j"${nproc_count}" distclean
}

export -f clean_target

valid_target_names=()

for target_name in "${@}"
do
	build_dir="${repo_dir}/build/${target_name}${SUFFIX:-}"

	if [ ! -d "${build_dir}" ]
	then
		continue
	fi

	valid_target_names+=("${target_name}")
done

for target_name in "${valid_target_names[@]}"
do
	echo "${target_name}"
done | xargs -I{} -P"${nproc_count}" bash -c 'clean_target {}'
