#! /usr/bin/env bash

# Copyright (c) 2026 Daemon Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Prints free memory in GB.

set -e -u -o pipefail

export LC_ALL='C.UTF-8'

default_mem='8'

case "$(uname -s)" in
	'Linux')
		free -g \
		| awk '/^Mem:/ {print $7}'
	;;
	'Darwin')
		vm_stat \
		| awk '
			/page size/ {
				match($0, /[0-9]+/)
				size=substr($0, RSTART, RLENGTH)
			}
			/Pages free/        { free=$3 }
			/Pages inactive/    { inactive=$3 }
			/Pages speculative/ { speculative=$3 }
			END {
				gsub("\\.","",free)
				gsub("\\.","",inactive)
				gsub("\\.","",speculative)
				print int((free+inactive+speculative)*size/1024/1024/1024)
			}'
	;;
	'FreeBSD')
		sysctl -n \
			vm.stats.vm.v_free_count \
			vm.stats.vm.v_inactive_count \
			vm.stats.vm.v_cache_count \
			vm.stats.vm.v_page_size  \
		| paste -s -d ' ' - \
		| awk '
			{
				print int(($1+$2+$3)*$4/1024/1024/1024)
			}'
	;;
	*)
		echo "${default_mem}"
	;;
esac | head -n 1 | sed -e "s/^0$/${default_mem}/"
