#! /usr/bin/env bash

# Copyright (c) 2025 Daemon Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u -o pipefail

default_job_count=4

if [ -n "${JOBS:-}" ]
then
	echo "${JOBS}"
	exit
elif command -v 'nproc' >/dev/null
then
	nproc
else
	case "$(uname -s)" in
		'Linux')
			grep -E "^processor" /proc/cpuinfo | wc -l
			;;
		'FreeBSD')
			sysctl -n hw.ncpu
			;;
		'Darwin')
			sysctl -n hw.logicalcpu || sysctl -n hw.ncpu
			;;
		'MSYS_NT-'*|'CYGWIN_NT-'*|'MINGW'*'_NT-'*)
			if command -v 'wmic' >/dev/null
			then
				wmic cpu get NumberOfLogicalProcessors/Format:List | grep -m1 '=' | cut -f2 -d'='
			else
				echo "${NUMBER_OF_PROCESSORS:-${default_job_count}}"
			fi
			;;
		*)
			echo "${default_job_count}"
			;;
	esac
fi
