#! /usr/bin/env python3

# Copyright (c) 2025 Daemon Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import base64
import json
import os
import requests

url = 'https://chromium.googlesource.com/native_client/src/native_client.git/+/refs/heads/main/toolchain_revisions/saigo_newlib.json?format=TEXT'
response = requests.get(url)
decoded = base64.b64decode(response.content)
content = json.loads(decoded)

archs = ["x86_64", "i686", "arm"]
packs = {
	"core_sdk_libs_saigo": "core",
	"libcxx_saigo": "libcxx",
	"libs_support_saigo": "support",
	"newlib_saigo": "newlib",
}

data={}
for arch in archs:
	data[arch] = {}
	for pack in packs:
		data[arch][pack] = {}

for archive in content["package_targets"]["linux_x86"]["archives"]:
	name = archive["name"]
	url = archive["url"]

	for arch in archs + ["x86_32"]:
		for pack in packs.keys():
			if name == "{}_{}.tgz".format(pack, arch):
				data[arch][pack]["url"] = url
				data[arch][pack]["target"] = "{}-{}".format(arch, packs[pack])

				# Workaround stupid CMake's “feature” that strips the first directory.
				if arch == "i686":
					dir_arch = "x86_64"
				else:
					dir_arch = arch

				if packs[pack] == "support":
					data[arch][pack]["subdir"] = "lib"
				else:
					data[arch][pack]["subdir"] = "{}-nacl".format(dir_arch)

content = ""

for arch in archs:
	for pack in packs.keys():
		p = data[arch][pack]
		content += """
AddTarProject("{}"
	"{}"
	"{}"
)""".format(p["target"], p["subdir"], p["url"])

dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
file_path = os.path.join(dir_path, "tarballs.cmake")

with open(file_path, "w", encoding="utf-8") as f:
	f.write(content)
